# Generated by Django 4.2.3 on 2023-07-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(default='', max_length=50)),
                ('product_sub_category', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('img', models.ImageField(default='', upload_to='shop/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
