# Generated by Django 4.2.3 on 2023-07-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_name_orders_fname_orders_country_orders_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='update1',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='update2',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='update3',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
